name: Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen graphviz
          version: 1.0
      - run: mkdir -p build/css
      - run: wget https://raw.githubusercontent.com/jothepro/doxygen-awesome-css/refs/heads/main/doxygen-awesome.css -O build/css/doxygen-awesome.css
      - run: doxygen .doxyfile
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: build/docs

