name: Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen
          version: 1.0
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip
      - run: pip install -r requirements.txt
      - run: doxygen-awesome-css --install build/css
      - run: doxygen .doxyfile
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: build/docs

